[client]
hawkbit_server = localhost
ssl = true
ssl_verify = false
target_name = rauc-device1
auth_token = i-am-a-token

tenant_id = DEFAULT
bundle_download_location = /tmp/bundle.raucb
poll_interval = 10

[device]
hw_boardname = rauc-device
hw_revision = 1.0b
sw_version = 0.1.0
