[system]
compatible=rauc-device-1.0b
bootloader=custom

[handlers]
bootloader-custom-backend=/usr/local/bin/bootloader
pre-install=/usr/local/bin/create-loop-devices
post-install=/usr/local/bin/restart-app

[keyring]
path=/etc/rauc/keyring.pem

[slot.app.0]
bootname=app0
type=ext4
device=/tmp/app0.img

[slot.app.1]
bootname=app1
type=ext4
device=/tmp/app1.img
