name: Docker

# on:
#   workflow_run:
#     workflows: ["PyPI"]
#     types:
#       - completed

on:
  push:
    branches:
      - "gardena/eb/ci"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set GOOSEBIT_VERSION env var
        run: |
          if [ $GITHUB_REF_TYPE = tag ]; then
            tag=$GITHUB_REF_NAME
          else
            tag=v0.1.2
          fi
          echo "GOOSEBIT_VERSION=${tag#v}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.6.1
        with:
          context: .
          build-args: GOOSEBIT_VERSION=${{ env.GOOSEBIT_VERSION }}
          file: ./Dockerfile
          push: false
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}

      # - name: Deploy website
      #   run: poetry run mkdocs gh-deploy
